services:

  # Configure the Grafana observability stack
  grafana-lgtm-stack:
    image: grafana/otel-lgtm
    container_name: lgtm-stack
    hostname: lgtm-stack
    profiles:
      - observability
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - prometheus:/prometheus
      - loki:/data/loki
      - grafana:/var/lib/grafana

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command:
      - "-config.file=/etc/promtail/promtail.yaml"
    profiles:
      - observability
    hostname: promtail
    restart: always
    depends_on:
      grafana-lgtm-stack:
        condition: service_healthy
    volumes:
      - ./observability/promtail/config.yaml:/etc/promtail/promtail.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  prometheus:
  grafana:
  loki:
  minio_loki:
  tempo_data:
