name: "Testing"

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'documentation/**'
      - '*.md'
      - 'docker-compose.yaml'
      - 'docker-compose.dev.yaml'
      - 'makefile'
  pull_request:
    types: [ opened,synchronize ]
    branches:
      - main

jobs:
  test:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20

      - name: Get dependencies and run tests
        run: |
          go mod download
          go test -v ./...